baseURL = "https://pubpro.dev/"
title = "pubpro.dev"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-9K2HQLYKR6"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "pubpro.dev"
description = "ExampleSite description"
keywords = ["Blog", "Portfolio", "PaperMod"]
author = "Me"
mainSections = ["posts", "newsletter", "packages"]
images = ["<link or path of image for opengraph, twitter-cards>"]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hideFooter = true
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

[params.label]
text = "pubpro.dev"
icon = "/apple-touch-icon.png"
iconHeight = 35

[params.profileMode]
enabled = false
title = "pubpro.dev"
subtitle = "This is subtitle"
imageUrl = "<img location>"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[params.homeInfoParams]
Title = "Pubpro.dev"
Content = """
Welcome to the blog section of pubpro.dev. **Pubpro.dev** is a **private** package hosting and marketing service. We currently support **[Dart](https://dart.dev) and [Flutter](https://flutter.dev)** packages. - Signup today at 🌟 [dart.pubpro.dev](https://dart.pubpro.dev). Reach out to us at contact@pubpro.dev.
"""

[[params.socialIcons]]
name = "host"
url = "https://pub.dev/publishers/pubpro.dev/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/pubpro-dev"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]


[[menu.main]]
identifier = "search"
name = "Search"
url = "search/"
weight = 1

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 2

[[menu.main]]
identifier = "newsleter"
name = "Newsleters"
url = "/newsletter/"
weight = 3

[[menu.main]]
identifier = "packages"
name = "Packages"
url = "/packages/"
weight = 4

[[menu.main]]
identifier = "host"
name = "dart.pubpro.dev"
url = "https://dart.pubpro.dev/"
weight = 30

[markup.highlight]
noClasses = false

[outputs]
home = ["HTML", "RSS", "JSON"]
